services:
  db:
    image: postgres:16.4-alpine
    container_name: task_manager_db_container
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapiappnetwork

  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: task_manager_app
    restart: always
    ports:
      - 8000:8000
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
      - smtp4dev
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - fastapiappnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    env_file:
      - .env.docker
    depends_on:
      - app
    networks:
      - fastapiappnetwork

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: always
    ports:
      - 3000:80
      - 2525:25
    env_file:
      - .env.docker
    networks:
      - fastapiappnetwork

volumes:
  postgres_data:

networks:
  fastapiappnetwork:
