version: "3"

services:
  db:
    image: postgres:13-alpine
    container_name: task_manager_db_container
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - 5433:5432
    networks:
      - fastapiappnetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: task_manager_app
    ports:
      - 8000:8000
    depends_on:
      - db
      - smtp4dev
    volumes:
      - .:/app
    networks:
      - fastapiappnetwork
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - fastapiappnetwork
    depends_on:
      - app
    restart: always

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - 3000:80
      - 2525:25
    environment:
      - SMTP4DEV_ADMIN_USERNAME=admin
      - SMTP4DEV_ADMIN_PASSWORD=password
    networks:
      - fastapiappnetwork

volumes:
  postgres_data:

networks:
  fastapiappnetwork:
