version: "3"

services:
  db:
    image: postgres:16.4-alpine
    container_name: task_manager_db_container
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapiappnetwork

  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: task_manager_app
    restart: always
    ports:
      - 8000:8000
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
      - smtp4dev
    volumes:
      - .:/app
    networks:
      - fastapiappnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
    env_file:
      - .env.docker
    depends_on:
      - app
    networks:
      - fastapiappnetwork

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: always
    ports:
      - 3000:80
      - 2525:25
    environment:
      - SMTP4DEV_ADMIN_USERNAME=$SMTP4DEV_ADMIN_USERNAME
      - SMTP4DEV_ADMIN_PASSWORD=$SMTP4DEV_ADMIN_PASSWORD
    env_file:
      - .env.docker
    networks:
      - fastapiappnetwork

volumes:
  postgres_data:

networks:
  fastapiappnetwork:
