version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - smtp4dev
    ports:
      - "8000:8000"

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "3000:80"
      - "2525:25"
    env_file:
      - ./.env

volumes:
  data:
